name: Submit to marketplace
description: Submit your plugin to be automatically validated and published on the marketplace.
title: '[plugin/adapter/bot]: xxx'
body:
  - type: markdown
    attributes:
      value: |
        请在标题中括号内填入类型，例如：[plugin]，冒号后附带插件名称，例如：[plugin]: xxx
  - type: input
    attributes:
      label: module-name
      description: 导入时的模块名称
  - type: input
    attributes:
      label: pypi-name
      description: 导入时的模块名称
  - type: markdown
    attributes:
      value: |
        感谢你的贡献，提交issue后将会进行自动审核。
